version: "3"
services:
  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - demo2
  demo2:
    build:
      ./build
    entrypoint: /demo2 --registry=consul --registry_address=consul:8500
    links:
      - consul
  micro:
    command: --registry=consul --registry_address=consul:8500 api --handler=api --namespace=anakin.sun.api
    image: microhq/micro:latest
    links:
      - consul
      - demo2
    ports:
      - "8080:8080"