version: "3"

services:
  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin -ui
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  api:
    build: ./api
    entrypoint: ./api --registry=consul --registry_address=consul:8500
    links:
      - consul
  user-service:
    build: ./user-service
    entrypoint: ./user-service --registry=consul --registry_address=consul:8500
    links:
      - consul
