version: "3"

services:
  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  jaeger:
    image: jaegertracing/all-in-one:1.8
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: mysql:5.7
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test123
  micro:
    command: --registry=consul --registry_address=consul:8500 api --handler=http --namespace=chope.co.api
    image: microhq/micro:latest
    links:
      - consul
      - api
    ports:
      - "8080:8080"
  api:
    build: ./build/api
    entrypoint: ./api --registry=consul --registry_address=consul:8500
    links:
      - consul
      - nats
      - jaeger
      - user-service
      - restaurant-service
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - api
  user-service:
    build: ./build/user-service
    entrypoint: ./user-service --registry=consul --registry_address=consul:8500 --broker=nats --broker_address=nats
    links:
      - db
      - redis
      - consul
      - nats
      - jaeger
      - restaurant-service
  restaurant-service:
    build: ./build/restaurant-service
    entrypoint: /restaurant-service --registry=consul --registry_address=consul:8500 --broker=nats --broker_address=nats
    links:
      - consul
      - nats
      - jaeger

